# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(485, 508)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_main = QtWidgets.QLabel(self.centralwidget)
        self.label_main.setGeometry(QtCore.QRect(160, 60, 153, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_main.setFont(font)
        self.label_main.setObjectName("label_main")
        self.label_result = QtWidgets.QLabel(self.centralwidget)
        self.label_result.setGeometry(QtCore.QRect(170, 100, 102, 13))
        self.label_result.setObjectName("label_result")
        self.Ceck_numbers = QtWidgets.QCheckBox(self.centralwidget)
        self.Ceck_numbers.setGeometry(QtCore.QRect(160, 150, 144, 17))
        self.Ceck_numbers.setObjectName("Ceck_numbers")
        self.checkBox_letters = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_letters.setGeometry(QtCore.QRect(160, 190, 145, 17))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_letters.setFont(font)
        self.checkBox_letters.setObjectName("checkBox_letters")
        self.Button_generate = QtWidgets.QPushButton(self.centralwidget)
        self.Button_generate.setGeometry(QtCore.QRect(180, 240, 75, 23))
        self.Button_generate.setObjectName("Button_generate")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_main.setText(_translate("MainWindow", "Генератр паролів "))
        self.label_result.setText(_translate("MainWindow", "Тут буде результат"))
        self.Ceck_numbers.setText(_translate("MainWindow", "Використовувати числа"))
        self.checkBox_letters.setText(_translate("MainWindow", "Використовувати букви"))
        self.Button_generate.setText(_translate("MainWindow", "Згенерувати"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
